version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    command: sh -c "
      python3 manage.py collectstatic --no-input
      && gunicorn backend.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
      - django-static:/backend/static
    ports:
      - "8000:8000"
volumes:
  django-static: